In [5]:
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([4,5,6,7,8])
print(np.absolute(a-b))
print(np.absolute((a-b)/b))

[3 3 3 3 3]
[0.75       0.6        0.5        0.42857143 0.375     ]


In [7]:
c=np.array([1,2,3,4,5])
d=np.array([1,2,3,4,6])
def bigger(a,b):
    for i in range(len(a)):
        if a[i]>b[i]:
            print(a[i])
        else:
            print(b[i])
print(c*2)
print("------------")
bigger(c,d)



NameError: name 'np' is not defined

In [10]:
equal=[(-1,25),(0,75)]
less=[(-1,25),(0,100)]
more=[(-1,100),(0,75)]
import bisect
bisect.bisect_left(more,(2,0))

2

In [16]:
a=[[1,1,2,0.35],[1,1,2,0.78]]
input=np.array([a,a,a])
print(input)
print(input.shape)

[[[1.   1.   2.   0.35]
  [1.   1.   2.   0.78]]

 [[1.   1.   2.   0.35]
  [1.   1.   2.   0.78]]

 [[1.   1.   2.   0.35]
  [1.   1.   2.   0.78]]]
(3, 2, 4)


In [44]:
a=np.zeros((5,1,2,4))
# print(a)
for i in range(5):
    for j in range(2):
        a[i][0][j][-1]=(i+j+5)/10
print(a)
print(np.min(a[:,0,:,-1],axis=1))

[[[[0.  0.  0.  0.5]
   [0.  0.  0.  0.6]]]


 [[[0.  0.  0.  0.6]
   [0.  0.  0.  0.7]]]


 [[[0.  0.  0.  0.7]
   [0.  0.  0.  0.8]]]


 [[[0.  0.  0.  0.8]
   [0.  0.  0.  0.9]]]


 [[[0.  0.  0.  0.9]
   [0.  0.  0.  1. ]]]]
[0.5 0.6 0.7 0.8 0.9]


In [5]:
import torch
from torch.utils.data import TensorDataset
from torch.utils import data 
a = torch.tensor([[1,1,1],[2,2,2],[3,3,3],[4,4,4]])
# b的第一维与a相同
b = torch.tensor([1,2,3,4])
c= torch.tensor([11,21,31,41])
train_data = TensorDataset(a,b,c)
train_loader = data.DataLoader(train_data,batch_size=2,shuffle=False)
print(train_data[0:4])
for i,(x,y,z) in enumerate(train_loader):
    print(x,y,z)
    print("-------------")

(tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4]]), tensor([1, 2, 3, 4]), tensor([11, 21, 31, 41]))
tensor([[1, 1, 1],
        [2, 2, 2]]) tensor([1, 2]) tensor([11, 21])
-------------
tensor([[3, 3, 3],
        [4, 4, 4]]) tensor([3, 4]) tensor([31, 41])
-------------


In [43]:
def C_prob(less_histogram,more_histogram,equal_histogram,screen_type,screen_value,total):
    #0:None   ;    1=   ;   2>=   ;  3<=    ;   4[]
    if screen_type==0:
        return [-1,1]
    elif screen_type==1:
        th=bisect.bisect(equal_histogram,(screen_value,0))
        return [screen_value/(equal_histogram[-1][0]-equal_histogram[0][0]),equal_histogram[th][1]/total]
    elif screen_type==2:
        th=bisect.bisect_left(more_histogram,(screen_value,0))
        if th==len(more_histogram):
            return [screen_value/(equal_histogram[-1][0]-equal_histogram[0][0]),0]
        else:
            return [screen_value/(equal_histogram[-1][0]-equal_histogram[0][0]),more_histogram[th][1]/total]
    elif screen_type==3:
        th=bisect.bisect_right(less_histogram,(screen_value,0))
        if th==0:
            return [screen_value/(equal_histogram[-1][0]-equal_histogram[0][0]),0]
        else:
            return [screen_value/(equal_histogram[-1][0]-equal_histogram[0][0]),less_histogram[th-1][1]/total]
    elif screen_type==4:
        th1=bisect.bisect_left(more_histogram,(screen_value[0],0))
        if th1==len(more_histogram):
            more_count=0
        else:
            more_count=more_histogram[th1][1]

        th2=bisect.bisect_right(less_histogram,(screen_value[1],0))
        if th2==0:
            less_count=0
        else:
            less_count=less_histogram[th2-1][1]
        return (more_count+less_count-total)/total

[[ -2.]
 [ -2.]
 [ -2.]
 [ -2.]
 [ -2.]
 [ -2.]
 [100.]
 [100.]
 [100.]
 [100.]]


/home/lyx15279830673/anaconda3/envs/ready/lib/python3.8/site-packages/torch/cuda/__init__.py:83: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 804: forward compatibility was attempted on non supported HW (Triggered internally at  ../c10/cuda/CUDAFunctions.cpp:109.)
  return torch._C._cuda_getDeviceCount() > 0


TypeError: where() received an invalid combination of arguments - got (numpy.ndarray, numpy.ndarray, int), but expected one of:
 * (Tensor condition)
 * (Tensor condition, Tensor input, Tensor other, *, Tensor out)
 * (Tensor condition, Number self, Tensor other)
      didn't match because some of the arguments have invalid types: (!numpy.ndarray!, !numpy.ndarray!, !int!)
 * (Tensor condition, Tensor input, Number other)
      didn't match because some of the arguments have invalid types: (!numpy.ndarray!, !numpy.ndarray!, !int!)
 * (Tensor condition, Number self, Number other)
      didn't match because some of the arguments have invalid types: (!numpy.ndarray!, !numpy.ndarray!, !int!)


In [4]:
import torch
flag = torch.cuda.is_available()
print(flag)

ngpu= 1
# Decide which device we want to run on
device = torch.device("cuda:0" if (torch.cuda.is_available() and ngpu > 0) else "cpu")
print(device)
print(torch.cuda.get_device_name(0))
print(torch.rand(3,3).cuda()) 


True
cuda:0
NVIDIA GeForce RTX 3090
tensor([[0.7230, 0.9345, 0.3499],
        [0.2436, 0.9583, 0.4768],
        [0.5262, 0.5660, 0.1395]], device='cuda:0')


In [1]:
a=[1,2,3]
b=[1,2,3,4,5,6,7,8]
print(b[len(a):])

[4, 5, 6, 7, 8]


In [5]:
import random

for i in range(10):
    n =random.randint(0,1)
    print(n)

1
1
1
0
1
0
1
0
1
0
